#!/usr/bin/env bash
# AI GENERATED FILE: DO NOT EDIT, REGENERATE FROM dump_to_rockable.msp INSTEAD.
# Prints the header of a .dump checkpoint file, taking the path as a real command-line argument
# (dump_inspector.msp alone requires editing "dump_inspector_target" by hand or passing an
# override file; this wrapper generates that override for you).
#
# Usage:
#   ./dump_inspector.sh <path/to/file.dump> [extra exaDEM args, e.g. --omp_num_threads 1]
#
# The exaDEM binary is looked up on PATH by default; set EXADEM_BIN to point at a specific one.
# dump_inspector.msp is looked up next to this script by default; set DUMP_INSPECTOR_MSP to
# override (used by the build-dir "dump_inspector" launcher generated by CMake).
set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <path/to/file.dump> [extra exaDEM args]" >&2
  exit 1
fi

DUMP_FILE="$1"
shift

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
EXADEM_BIN="${EXADEM_BIN:-exaDEM}"
DUMP_INSPECTOR_MSP="${DUMP_INSPECTOR_MSP:-$SCRIPT_DIR/dump_inspector.msp}"

TMP_MSP="$(mktemp --suffix=.msp)"
trap 'rm -f "$TMP_MSP"' EXIT

cat > "$TMP_MSP" <<EOF
dump_inspector_target:
  - dump_inspector:
     filename: "$DUMP_FILE"
EOF

"$EXADEM_BIN" "$DUMP_INSPECTOR_MSP" "$TMP_MSP" "$@"
