name: CMake
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - uses: actions/setup-node@v4
    - name: Get Yaml cpp
      run: sudo apt install libyaml-cpp-dev
    - name: Install
      run: sudo apt-get update && sudo apt-get install lcov
#    - uses: mpi4py/setup-mpi@v1
#      with: 
#        mpi: openmpi
    - name: Install MPI
      run: sudo apt install mpich
      
    - name: Get Onika
      run: git clone https://github.com/Collab4exaNBody/onika.git
      working-directory: ${{github.workspace}}/onika           
    - name: Configure Onika
      run: cmake -B ${{github.workspace}}/onika/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_INSTALL=${{github.workspace}}/onika/install
      working-directory: ${{github.workspace}}/onika    
    - name: Build Onika
      # Build your program with the given configuration
      run: cmake --install --build ${{github.workspace}}/onika/build --config ${{env.BUILD_TYPE}} -j 2 
      
    - name: Get ExaNBody
      run: git clone https://github.com/Collab4exaNBody/exaNBody.git
      working-directory: ${{github.workspace}}/exaNBody          
    - name: Configure ExaNBody
      run: cmake -B ${{github.workspace}}/exaNBody/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_INSTALL=${{github.workspace}}/exaNBody/install -Donika_DIR=${{github.workspace}}/onika/install
      working-directory: ${{github.workspace}}/exaNBody   
    - name: Build ExaNBody
      # Build your program with the given configuration
      run: cmake --install --build ${{github.workspace}}/onika/build --config ${{env.BUILD_TYPE}} -j 2
      
    - name: Configure CMake
      run: cmake -DCMAKE_CXX_FLAGS="--coverage -g" -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DexaNBody_DIR=${{github.workspace}}/exaNBody/install

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 2

    - name: Test Example
      working-directory: ${{github.workspace}}/build
      run: make UpdatePluginDataBase && ctest --test-dir example -C --rerun-failed --output-on-failure ${{env.BUILD_TYPE}}

    - name: Generate a code coverage repor part1
      uses: threeal/gcovr-action@v1.1.0
      with:
        html-details: true
        html-theme: github.green
        gcov-executable: gcov
#        root:  ${{github.workspace}}/
        root: ${{github.workspace}}/build/src/
        excludes: |
          exaNBody

    - name: Generate a code coverage report part2
      working-directory: ${{github.workspace}}/
      run: gcovr --exclude='exanb/*' --exclude='onika/*' --exclude='exaNBody/*' --exclude='build/*' --gcov-ignore-parse-errors=suspicious_hits.warn --html-details coverage.html

    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: ${{github.workspace}}/coverage.html        
